### ISSUE TITLE
Makefile Support for @

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#118]
Multiple Java Makefiles use the `@` before a command.
- [ ] read the [docs](https://www.gnu.org/software/make/manual/make.html#Echoing)
- [ ] Implement of filter the `@`

Maybe ignore it via the regex

**Comment by MrSerth** [comment]
Oh yes, indeed! We use the `@` to suppress the `javac ...` and `java ...` commands and hide them from our learners. I totally forgot about that when designing the Makefile support - sorry for that! 🙈
