### ISSUE TITLE
AWS: Missing newline

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#121]
The newline of the execution of `System.out.println("Hallo Welt");` is missing.

**Comment by MrSerth** [comment]
Shouldn't we have some newlines in here? 🤓 

**Current:**
<img width="710" alt="Bildschirmfoto 2022-04-24 um 17 43 34" src="https://user-images.githubusercontent.com/7300329/164984589-e44081ec-0390-4afc-89e2-581f1f433047.png">

<img width="705" alt="Bildschirmfoto 2022-04-24 um 17 43 42" src="https://user-images.githubusercontent.com/7300329/164984597-939ef9e1-b7d3-460a-a4a4-009a0a6b4434.png">

**Expected:**
<img width="704" alt="Bildschirmfoto 2022-04-24 um 17 45 00" src="https://user-images.githubusercontent.com/7300329/164984620-93124ae2-5cb7-43a7-8439-11407a157521.png">

<img width="703" alt="Bildschirmfoto 2022-04-24 um 17 44 05" src="https://user-images.githubusercontent.com/7300329/164984603-b8f0db17-dfae-4cbc-8c0d-5f25facb5ffc.png">

**Comment by mpass99** [comment]
That's weird!

I can recreate the problem on CodeOcean, but both Java11Exec and Poseidon send the newline back....
![Postman Log](https://user-images.githubusercontent.com/22845248/164985799-5e9acf2b-f66d-464b-bc95-2fbc423cf416.png)

Could it be that CodeOcean needs "\r\n"? Or do you have another idea?

**Comment by mpass99** [comment]
Yup, `System.out.println("Hallo Welt\r");` works

**Comment by MrSerth** [comment]
Hm, we do some nasty things with both line terminators, such as [here](https://github.com/openHPI/codeocean/blob/18daa1c998bcc182f1006faa415e70a27e9efa8c/lib/runner/connection/buffer.rb#L70-L77).

For Nomad, this hasn't been a problem so far -- do we get `\r\n` from Nomad? Otherwise, I wondered how that ever worked ...

**Comment by mpass99** [comment]
Yes, Nomad sends us `{"type":"stdout","data":"Hallo Welt\r\nHallo Welt\r\n"}`..

**Comment by MrSerth** [comment]
Thanks for confirming. I made a PR for CodeOcean https://github.com/openHPI/codeocean/pull/1241 and applied that fix already for the [linked exercise](https://codeocean.openhpi.de/exercises/1005/implement).
