### ISSUE TITLE
AWS: Tests cannot get executed

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#124]
I tried the AWS Hello World again and noticed that the `Score` functionality is currently broken.

Instead of executing the tests, it simply returns:

```
StdErr: sh: make: command not found
```

Also, in CodeOcean, we should switch to JUnit 4 (from JUnit 5) for the AWS environment (as this is the version the tests are written in).

**Comment by mpass99** [comment]
This is because our Makefile implementation does not recognise `make test CLASS_NAME="%{class_name}" FILENAME="%{filename}"` as valid make command matching the pattern `^make(?:\s+(?<startRule>\w*))?$`.

Should we implement the make feature of make variables? We should also keep in mind that there are other possibilities, such as putting a static make binary (+ dependencies if necessary) into the aws deployment.

**Comment by MrSerth** [comment]
Hm, that's another edge case for Make, true. I would hope, it is the last one...

Regarding the tests: Do you know whether they will work once we fixed that make problem? I am asking as we are also including JUnit 4 with two jars which might or might not be available in AWS. Probably using JUnit 5 is no problem, but any JUnit is required.

**Comment by mpass99** [comment]
Regarding the tests: We can include all dependencies via our maven [pom.xml](https://github.com/openHPI/poseidon/blob/main/deploy/aws/java11Exec/pom.xml) file.

For example, if we remove the test-scope of our junit dependency...

https://github.com/openHPI/poseidon/blob/bb2d989bc51680a29e8c7ebb1ea014ae647b32ac/deploy/aws/java11Exec/pom.xml#L35-L40

... we can access `junit.junit-4.13.1.jar` in the folder `/var/task/lib`.
How do we deal with the problem that the path to the library is set statically in the Makefile, but differs between Nomad and AWS?

**Comment by MrSerth** [comment]
Okay, that's fine. We use that dependency and Hamcrest (in addition):

```
<!-- https://mvnrepository.com/artifact/org.hamcrest/hamcrest-core -->
<dependency>
    <groupId>org.hamcrest</groupId>
    <artifactId>hamcrest-core</artifactId>
    <version>1.3</version>
</dependency>
```

My proposal (for a quick solution, but not tested yet):

```
.map(s->s.replaceAll("/usr/java/lib/hamcrest-core-1.3.jar", "/<new path>.jar"))
.map(s->s.replaceAll("/usr/java/lib/junit-4.11.jar", "/<new path>.jar"))
```

This might work somewhere in the stream of the `SimpleMakefile`, I hope 🤞 
Do you think this could work?

**Comment by mpass99** [comment]
> Do you think this could work?

Yes, it's a very quick fix :+1:

Unfortunately, [the "Score" result](https://codeocean.openhpi.de/exercises/1005/implement) only turned from red to orange..

**Comment by MrSerth** [comment]
That's easy to fix -- I already did so. Remember my initial comment?

> Also, in CodeOcean, we should switch to JUnit 4 (from JUnit 5) for the AWS environment (as this is the version the tests are written in).

In CodeOcean, we use some output parsing (with RegEx) to identify the score. When this is set to the wrong version, our RegEx doesn't match 😁
