### ISSUE TITLE
Java11Exec: Visible credentials

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#130]
The AWS lambda function contain the credentials of the specific lambda execution role as environment variables. With `env` you can read them and use them for requests with your AWS cli. The iam role for the lambda function has not many permissions but I was able to create Logs (and Log groups) via those credentials.

As a measure we can on the one hand hide all environment variables during execution and on the other hand remove the permission to write logs, as we don't use the logs anyway.

**Comment by mpass99** [comment]
Since the lambda function responds via WebSocket, it also has permission to access all active connections. However, since there is no listing of active connections, the 11-byte connection id would have to be determined by brute force.

**Comment by MrSerth** [comment]
We decided to remove some of the variables and also add `CODEOCEAN=true`.
