### ISSUE TITLE
Enable file transfer from allocations to CodeOcean

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#136]
So far, we have a one-way file copy mechanism, which allows CodeOcean to send files to an allocation. These files usually contain the user's source code or some other resources required for the execution.

In some circumstances, we are also interested in receiving files generated during the execution within the allocation and would like to receive them. For example, a user in the R course might use R to generate a graph using code and some input data, which is consequently exported as a PDF file. This PDF file is generated within the allocation and, so far, we don't have any mechanism to provide the user with a download link to this PDF. Therefore, I suggest investigating how we may receive these artifacts.

As a user,  
I want to receive the files generated with my source code   
in order to download and review them on my local machine.

<hr>

In order to implement this feature, we could design an additional API for Poseidon that CodeOcean uses. Ideally, we have two routes: One for receiving a *list* of files (and all sub-directories) in `/workspace` (if not specified differently) with some basic information (such as the file name incl. file extension, file size, maybe modification date) and another one for retrieving the actual *content* of files (with an option to receive either all files or only those selected). When offering the files for download (in CodeOcean), we should also remove any file that was sent to Poseidon previously (as that might contain hidden test script files) or derived from a file we sent (such as `.class` files for matching `.java` files). Ideally, the list of all files would have an additional flag whether the file was created by the user or us, but if that is too hard, we just filter them by name in CodeOcean).

As this is a quite complex feature, we might start with designing the API and some MVP to validate the feasibility of this request.

**Comment by mpass99** [comment]
To reduce the attacking surface Poseidon and CodeOcean could both act [just as proxy](https://ruby-doc.org/stdlib-2.4.1/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-Streaming+Response+Bodies) for the file download?!

As this on-demand streaming is not possible with AWS Functions we are now focussing on Nomad and postpone the AWS solution at this moment.

**Comment by MrSerth** [comment]
I assume that a proxy for the file download would be totally fine; this is a nice (and performant) idea. As of now, I don't think we need to store a copy of the files offered for learners (similar to the testrun_messages), and thus streaming is fine. I was just considering offering an archive of "all" files generated during a run (maybe in addition to the individual files), but this could be well done by CodeOcean if needed. 

Also, postponing AWS is a good proposal, we're more about to test that first ;)
