### ISSUE TITLE
AWS: Automated deployment

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#171]
As a developer  
I want to develop my AWS application  
without a high risk of production issues in case of a bug.

----

1. We may introduce an AWS `test` stage in order to be able to test changes to the AWS application efficiently.
2. We may introduce a CI stage [that is triggered only on changes within the AWS path](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths) and that automatically deploys the aws application to the `test` stage.
3. We may run our e2e tests against the AWS `test` stage.
4. We may automatically `production` deploy on a merge to main.

Limitations:
- Multiple PR modifying the AWS application may interfere with each other.
  - [Local testing is not supported for WebSocket APIs](https://github.com/aws/aws-sam-cli/issues/896)

**Comment by MrSerth** [comment]
Based on our findings in #218, this issue became obsolete and won't be tackled (in the current form). Therefore, I am closing it for now.
