### ISSUE TITLE
Fix count of storage monitoring

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#178]
The count field of the monitored data contains odd numbers like `9223372036854776000`, `0.5` or `2.5`.

**Comment by mpass99** [comment]
The scope of this issue is now much smaller. It may been partially fixed by 6e52b8660d834930dd6985ae8b77ad7f7ae674fc.
The remaining issue is that only in the measurement `poseidon_used_runners` often the odd number `18446744073709552000` appears. Probably an off-by-one underflow..

**Comment by mpass99** [comment]
This odd number has not appeared in the last week.
```flux
from(bucket: "poseidon/autogen")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "poseidon_used_runners")
  |> filter(fn: (r) => r["_field"] == "count")
  |> filter(fn: (r) => r._value > uint(v: 100))
  |> group()
  |> last()
```

**Comment by MrSerth** [comment]
> This odd number has not appeared in the last week.

Probably, there usage is currently too low to reproduce that quickly.... (or we fixed it 🎉 )

**Comment by mpass99** [comment]
Until now no new high or fractional numbers.

**Comment by MrSerth** [comment]
Great, let's close this issue :+1:
