### ISSUE TITLE
Refactoring: Use context of request

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#191]
At this moment we do not use the context of the requests made to Poseidon (`request.Context()`).

So even if the client (CodeOcean) is aborting the http connection, Poseidons calculations are not aborted.

**Comment by MrSerth** [comment]
I like the idea of cancelling requests, especially `GET` requests as they only read existing data. However, we should check the consequences of requests that change or persist data (such as `POST` requests) and the impact of cancelling those.

**Comment by mpass99** [comment]
I checked all routes and could divide them into the following groups:

- ListFileSystem, GetFileContent: Here, cancelling the request is useful. Anyways, the implementation already uses the request context.
- ExecuteCommand: Here, cancelling the request is useful. It is already implemented via the WebSocket Close Handler. That seems more complicated but I would anyways leave it that way for now.
- ListEnvironments: Here, cancelling the request would be a little useful. However, the Nomad client does not support the use of a context for those underlying requests.
- Routes that provide just in-memory data (GetEnvironment, EnvironmentStatistics, ProvideRunner): We do not have time intensive parts that could use a context effectively.
- Routes that should be executed even if the request is aborted (CreateOrUpdateEnvironment, DeleteEnvironment, UpdateFileSystem, Execute (aka GetWebSocketURL), DeleteRunner): In these cases, we already received the request. We should execute it not for the response but for side-effects.

All in all, I found no reasons for refactoring.

**Comment by MrSerth** [comment]
Okay, thanks for checking. Based on your findings and the explanation given, I agree with your summary that there seems to be no need for a refactoring currently. Let's close this ticket now and try to remember using a context where useful in the future.
