### ISSUE TITLE
Editing an environment with a new Docker image might duplicate the environment on Grafana

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#203]
Today, I was adding a new environment to CodeOcean. Unfortunately, I had to adjust the settings a few times and also switched the Docker image I used. As a result, our Grafana dashboards duplicated the environment (which has the ID 33). We should ensure that only the newest environment details are shown (based on the ID which is unique and the timestamp).

<img width="1727" alt="Bildschirmfoto 2022-08-26 um 20 00 47" src="https://user-images.githubusercontent.com/7300329/186964968-2c5d010f-7988-42c2-b389-2c27324123b5.png">

**Comment by mpass99** [comment]
Good catch, before it was the latest environment detail based on id, image, and stage; now it's only id and stage - by adding
``` flux
  |> group(columns: ["id", "stage"], mode:"by")
```

**Comment by MrSerth** [comment]
Awesome, thanks! I just checked the dashboard again and made similar changes. This time, updated Docker images are correctly processed and shown expected.
