### ISSUE TITLE
OpenAPI Definition - Add Token Header and Version Prefix to Path

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#209]
In our swagger definition we specify for many routes the `401 Unauthorized` response. Having only this document, this raises the question of how to authenticate.

This may be the appropriate place to add the information about our `Poseidon-Token`:
```openAPI
          parameters:
            - in: header
              name: Poseidon-Token
              schema:
                type: string
                format: password
              required: true
```
https://swagger.io/docs/specification/describing-parameters/#header-parameters

**Comment by MrSerth** [comment]
Good catch. We should also ensure to add the `api/v1` path prefix, which is not yet included in the documentation. Therefore, I generalised this ticket.
