### ISSUE TITLE
Start Daemons in Docker Image

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#211]
Obviously, we don't start our containers with the `/sbin/my_init` script, that is provided by our [Phusion base image](https://github.com/phusion/baseimage-docker).

The startup script `/sbin/my_init` needs to be executed as root user and can be further [customized to allow additional daemons to be started](https://github.com/phusion/baseimage-docker#running-scripts-during-container-startup). I tried replacing the `sleep infinity` command in `job.go` with `/sbin/my_init`, which didn't work due to the different users (`root` vs `user`). Do we have another idea on how to execute this task as `root` instead (either through Nomad during the execute call or using some Linux mechanism, such as the setuid bit for the file)?

**Comment by koelibri** [comment]
The main reason for providing `/sbin/my_init` as startup script in [Phusion base image](https://github.com/phusion/baseimage-docker) is proper handling of child processes. Starting additional daemons was another issue being addressed by this script. However, starting additional daemons could be done in other stages of Nomads job management. So, what really matters is a solution for proper handling of child processes 
`sleep infinity` clearly does not solve that problem. For obvious reasons the `sleep` command is not aware of any child processes at all. Starting and eventually stopping additional daemons will therefore result in zombie processes overcrowding the process table over time.
Instead `/bin/sh -c 'sleep infinity'` might be executed initially. As a matter of consequence `/bin/sh` becomes the PID 1 process being able to properly handle child processes and SIGCHLD signals. `sleep infinity` becomes a never ending subprocess which in turn prevents its parent process from terminating. To implement this behavior lines 20 and 36 in `job.go` need editing.

**Comment by koelibri** [comment]
If the developer team wishes to allow additional daemons to be started at boot time and therefore might claim a noteworthy amount of system resources even in prewarmed state, a sufficient means might be the use of Dockers `ENTRYPOINT` command or `--entrypoint` command line option. The `TaskCommand` and `args` config options at lines 20 and 36 in `job.go` should then be treated differently, i.e. as default values for cases where no `ENTRYPOINT` was defined in the Docker image. 

Using `ENTRYPOINT` will enable providers of execution environments to run another service as PID 1 process according to their particular use case. If someone wishes to start more than one daemon, the `cron` command would be sufficient as the entrypoint. In either case the Poseidon documentation should clearly state that only non-terminating commands with the ability to handle child processes, i.e. services, are suited as startup commands.

**Comment by koelibri** [comment]
If the developer team wishes to allow running `/sbin/my_init` as startup script, then instantiating and prewaerming containers should be done as `root`. As a matter of consequence every subsequent `exec` call on existing, prewarmed containers should then be executed using the `-u` option of the `docker exec` command to set the user to `user`. This should prevent normal end users from gaining root access on containers or the Poseidon/Nomad system.

**Comment by MrSerth** [comment]
Thanks for your thoughts and the work you've done. Based on your requirements and your feedback, I drafted https://github.com/openHPI/dockerfiles/pull/23 and #215 to solve this issue.

Unfortunately, Nomad does not allow to specify a different user for executing a command within an allocation in their `nomad alloc exec` command (see [documentation](https://www.nomadproject.io/docs/commands/alloc/exec)) as opposed to Docker with `docker exec`. Therefore, we're using the `/sbin/setuser` script available in our images to achieve this functionality.

**Comment by MrSerth** [comment]
With support in CodeOcean (https://github.com/openHPI/codeocean/pull/1377), all-new Docker images (see [here](https://github.com/openHPI/dockerfiles/actions) or below) and the PR in #215, this feature is implemented and available.

<img width="923" alt="Bildschirmfoto 2022-09-24 um 23 07 43" src="https://user-images.githubusercontent.com/7300329/192118821-42f52b8a-d415-42fc-94ec-7322993d821b.png">
