### ISSUE TITLE
Synchronizing execution environments might not work

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#22]
I noticed some strange errors when synchronizing (all) execution environments a few times repeatedly. In CodeOcean, I see an error: 

![Bildschirmfoto 2021-10-29 um 09 40 48](https://user-images.githubusercontent.com/7300329/139395473-0ef1f308-7863-478d-8eef-24609fc44aa1.png)

In my tests, this error is permanent as soon as it occurred once and thus should be fixed.

In Poseidon, I see the following log output:

`
2021/10/29 09:36:11 http: superfluous response.WriteHeader call from github.com/openHPI/poseidon/pkg/logging.(*loggingResponseWriter).WriteHeader (logging.go:50)
`

In Ruby, the following line is logged:

`
Could not create execution environment in Poseidon, got response: {"status"=>500, "body"=>"{\"message\":\"error registering template job in API: couldn't register job: error registering Nomad job: Put \\\"http://localhost:4646/v1/jobs?namespace=default\\\": EOF\",\"errorCode\":\"UNKNOWN\"}", "response_headers"=>{"content-type"=>"application/json", "date"=>"Fri, 29 Oct 2021 07:36:11 GMT", "content-length"=>"187"}}
`

**Comment by mpass99** [comment]
I see in the log that you are running Nomad on localhost. According to our normal Nomad start command, we do not use any configuration. However, in staging and production we use the config, which contains the following:
```
limits {
    http_max_conns_per_client = 0
}
```
Nomad has a more or less hidden limit of requests per user, as found in [this issue](https://gitlab.hpi.de/codeocean/codemoon/poseidon/-/issues/88). If I remember correctly, this also threw this non-specific error message. You can adjust the localhost configuration as [described here](https://www.nomadproject.io/docs/configuration).
The theory is also supported by the fact that I cannot recreate the error in the staging environment.

However, I noticed during the test that all runners are restarted when all environments are synchronised. Also we should investigate why an update environment request that does not change any information still takes 13s in staging.

**Comment by MrSerth** [comment]
Indeed - thanks for pointing that out. By applying the config option you posted above, I was able to synchronize and use the execution environments infinitely. Even though I am still wondering why the limit kicks in (it is about _concurrent_ HTTP requests which we shouldn't have), changing this setting resolves the issue for me.

**Comment by mpass99** [comment]
Thanks for pointing out that we are talking about _concurrent_ HTTP requests!
At one point we actually left requests open by mistake. This will be fixed in PR #28.

**Comment by mpass99** [comment]
The other issue about the 13 seconds for updating just one environment is because we update each Runner of that environment in a synchronous manner. This can be seen in the following log:
```
time="2021-11-03T15:43:02.695687Z" level=debug msg="Api: Before CreateOrUpdate" package=api
time="2021-11-03T15:43:02.695954Z" level=info msg="EnvironmentManager: After SetEnvironment" package=environment
time="2021-11-03T15:43:03.248572Z" level=info msg="EnvironmentManager: After Register" package=environment
time="2021-11-03T15:43:03.326051Z" level=debug msg="Environment: After LoadRunnerIDS" package=environment
time="2021-11-03T15:43:03.892437Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:04.421008Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:04.960100Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:05.512184Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:05.711800Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:06.239721Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:06.773264Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:07.293836Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:07.822617Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:08.374006Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:08.891882Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:09.097159Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:09.632739Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:10.164821Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:10.710305Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:11.248316Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:11.444779Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:11.995982Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:12.574811Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:13.109285Z" level=debug msg="After Register Runner Job" package=environment
time="2021-11-03T15:43:13.109310Z" level=info msg="EnvironmentManager: After UpdateRunnerSpecs" package=environment
time="2021-11-03T15:43:13.109325Z" level=debug msg="Removing idle runners" id=12 package=environment runnersToDelete=0
time="2021-11-03T15:43:13.109336Z" level=info msg="EnvironmentManager: After Scale" package=environment
time="2021-11-03T15:43:13.109343Z" level=debug msg="Api: After CreateOrUpdate" package=api
time="2021-11-03T15:43:13.109361Z" level=debug code=204 duration=10.413732789s method=PUT path=/api/v1/execution-environments/12 user_agent=PostmanRuntime/7.28.4
```
I see two measures to improve the situation.
1. we should request the runners asynchronously and only log them if something goes wrong
2. we should check at the beginning whether anything changes at all in the environment and if not just skip everything.

**Comment by MrSerth** [comment]
> The other issue about the 13 seconds for updating just one environment is because we update each Runner of that environment in a synchronous manner. 

Alright, that's good to know. I would propose to extract this issue in a new ticket so that we can track it independently of the concurrent HTTP issue.

> I see two measures to improve the situation.
> 
> 1. we should request the runners asynchronously and only log them if something goes wrong
> 2. we should check at the beginning whether anything changes at all in the environment and if not just skip everything.

Two great ideas here. As the synchronization is not performed that often, I would probably not choose an asynchronous sync mechanism but rather wait and display potential errors to the administrator. Maybe we should go with the second approach and only synchronize changes (if any)?
