### ISSUE TITLE
E2E tests are flaky

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#220]
- https://github.com/openHPI/poseidon/actions/runs/3119787868 (Three attempts needed)
- https://github.com/openHPI/poseidon/actions/runs/3156081185 (Three attempts needed)
- https://github.com/openHPI/poseidon/actions/runs/3180400642 (Two attempts needed)
- https://github.com/openHPI/poseidon/actions/runs/3180433119 (Two attempts needed)
- https://github.com/openHPI/poseidon/actions/runs/3180535020 (Two attempts needed)
- https://github.com/openHPI/poseidon/actions/runs/3187167812 (Three attempts needed)

**Comment by mpass99** [comment]
- https://github.com/openHPI/poseidon/actions/runs/3245764878 (Four attempts needed)

**Comment by MrSerth** [comment]
I observed another occurrence of this behaviour with the newest `main` branch. Would you mind having another look, please? Here's the occurrence:

- https://github.com/openHPI/poseidon/actions/runs/3312042210/jobs/5468333080 (Two attempts needed)
