### ISSUE TITLE
Leverage file system ACLs for copied files

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#236]
As a _user_
I want to _create files in an existing subdirectory_
in order to _compile Java classes in packages_. 

<hr>

As an administrator, I have the following requirements:

- [ ] Copied files should neither be writable nor deletable by non-privileged users (but privileged users)
- [ ] Folders (and the original workspace) created during the copy operation should allow the creation of new files by non-privileged users (even when the folder was created by a privileged user)

<hr>

We could think of either using the immutable flag (`chattr +i`, requires `LINUX_IMMUTABLE` for the container) or ACLs (`setfacl`, requires file system and kernel support). 

I would start by looking into ACLs if possible, but am also open to any other suggestion. 

_Based on / Part of #226_

**Comment by mpass99** [comment]
The ACLs look good but what is about the [sticky bit](https://en.wikipedia.org/wiki/Sticky_bit)?

> For directories, when a directory's sticky bit is set, the filesystem treats the files in such directories in a special way so only the file's owner, the directory's owner, or [root user](https://en.wikipedia.org/wiki/Root_user) can rename or delete the file. Without the sticky bit set, any user with write and execute permissions for the directory can rename or delete contained files, regardless of the file's owner. Typically this is set on the [/tmp directory](https://en.wikipedia.org/wiki/Temporary_directory) to prevent ordinary users from deleting or moving other users' files.

Could we just set the sticky bit (`1777`) for all folders (within `/workspace` (Poseidon has no clue about this folder by now))?
As an alternative, we can implement #226 and additionally extend the route schema for an `isDirectory` flag. This way CodeOcean could send all folders with `privileged=false` that would result in the sticky bit set?!

**Comment by MrSerth** [comment]
Awesome, that's a really good finding! I just tested various scenarios with the sticky bit and think it might address all our requirements (without using the much more complicated ACLs or immutable bit). I'd say: Go for it 🏁

**Comment by mpass99** [comment]
> This way CodeOcean could send all folders with `privileged=false` that would result in the sticky bit set?!

For me this question remains: CodeOcean already parses the directories from the paths provided by the files/teachers. Should Poseidon also parse (/split) the directories from the paths of the provided files or should CodeOcean send the required directories ([by a following `/`](https://github.com/openHPI/poseidon/blob/160df3d9e66b4d2447def2a7d4ed2ddf80d80d7b/pkg/dto/dto.go#L154-L157))? By now, CodeOcean only sends the files (not the directories).

**Comment by MrSerth** [comment]
> > This way CodeOcean could send all folders with `privileged=false` that would result in the sticky bit set?!
> 
> For me this question remains: CodeOcean already parses the directories from the paths provided by the files/teachers. Should Poseidon also parse (/split) the directories from the paths of the provided files or should CodeOcean send the required directories ([by a following `/`](https://github.com/openHPI/poseidon/blob/160df3d9e66b4d2447def2a7d4ed2ddf80d80d7b/pkg/dto/dto.go#L154-L157))? By now, CodeOcean only sends the files (not the directories).

Sure, I think this is not an issue. I created https://github.com/openHPI/codeocean/pull/1410 to copy the directories first, in conjunction with your newest PR.
