### ISSUE TITLE
Deleting an execution environment logs a warning for the template job

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#29]
When synchronizing an execution environment and deleting it immediately afterward, I get a warning message in Poseidon regarding the template job:

```
time="2021-11-03T22:04:39.111388Z" level=debug msg="Creating new runners" id=36 package=environment runnersRequired=2
time="2021-11-03T22:04:39.130869Z" level=debug code=201 duration=30.127ms method=PUT path=/api/v1/execution-environments/36 user_agent="Faraday v1.8.0"
time="2021-11-03T22:04:39.141110Z" level=debug msg="Removing idle runners" id=36 package=environment runnersToDelete=0
time="2021-11-03T22:04:39.144703Z" level=debug code=204 duration=3.596ms method=DELETE path=/api/v1/execution-environments/36 user_agent="Faraday v1.8.0"
time="2021-11-03T22:04:40.005374Z" level=debug msg="Runner started" id=36-a8594db0-3ce9-11ec-b33b-acde48001122 package=runner
time="2021-11-03T22:04:40.006075Z" level=debug msg="Runner started" id=36-a85a7528-3ce9-11ec-b33b-acde48001122 package=runner
time="2021-11-03T22:04:40.007764Z" level=debug msg="Runner stopped" id=template-36 package=runner
time="2021-11-03T22:04:40.007806Z" level=warning msg="Stopped allocation can not be handled" error="invalid environment id par strconv.Atoi: parsing \"template\": invalid syntax: invalid job id" package=runner
```

This might happen (rarely) in case of CodeOcean saving a new Execution Environment within a transaction and then rolling it back due to an error.

**Comment by mpass99** [comment]
This should occur every time an Execution Environment is deleted.
The DELETE request is completed when Nomad theoretically thinks that everything will be successful. Then the allocation is actually removed. The result of this is communicated to Poseidon via the event stream. But Poseidon does not care if an Execution Environment has actually been deleted, as it will then have nothing to do (it only needs to do something on stopped runners). Therefore, we do not catch this case.
A solution to this issue would be to produce a different (or no) log message for the specific case of the Execution Environment.
