### ISSUE TITLE
Specify requirements on Docker images

### ISSUE THREAD

**Issue by sirkrypt0** [openHPI/poseidon#3]
As a **user**,  
I want to know the requirements on the Docker images Poseidon can operate on,  
in order to avoid failures due to missing commands.

Currently, file copying inside the container is done using `tar --extract --absolute-names --verbose --file=/dev/stdin`. However, in Alpine containers, for example, the `tar` command does not know the `--absolute-names` option.

There might be other places in the code where implicit assumptions on the functionality available inside the Docker container are made. Those should be specified.

**Comment by MrSerth** [comment]
We need the following commands:
- mkfifo
- tar
- sleep
- cat
- rm

... and others
