### ISSUE TITLE
Flapping E2E tests, once again

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#348]
It just took me three attempts to pass the E2E tests, I haven't investigated why. See the [logs for the successful run here](https://github.com/openHPI/poseidon/actions/runs/4600724303) and choose an older attempt.

**Comment by MrSerth** [comment]
[Here](https://github.com/openHPI/poseidon/pull/427) is an example of another unreliable E2E test, which had to be restarted.

**Comment by mpass99** [comment]
- TestE2ETestSuite/TestEnvironmentVariables [[1]](https://github.com/openHPI/poseidon/actions/runs/6496654286/job/17644630136)
