### ISSUE TITLE
Handle lost, pending allocations

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#357]
In a recent downtime of one Nomad Agent we observed a new process we do not handle by now.

When runners are provided to users, another runner is started to refill the prewarming pool. In the process of being started, the allocation needs to be scheduled and started. In this time the allocation has the `ClientStatus` `pending`. When in this moment the Nomad agent  - that just starts the allocation -is going down, Nomad informs us with an event that the `ClientStatus` is `pending` but the `DesiredStatus` is `stop`. We convert the missing handling of this edge case into the warning `Other Desired Status` ([POSEIDON-2E](https://codeocean.sentry.io/issues/4052530553/?referrer=github_integration)).

**Open Question**: Why do we not receive an Event with the `ClientStatus` `lost` and the `DesiredStatus` `stop` like usual?

The downtime leads also to another error: `Started Runner is already in use` ([POSEIDON-2G](https://codeocean.sentry.io/issues/4061207219/?referrer=github_integration)). This can not be explained by the events that we have seen in the other warning as `pending` runners are not "started".

It shows us that also the runners with the `ClientStatus` `running` are lost but our warning about the `Other Desired Status` does not monitor this edge case.

Acceptance Criteria:
- [ ] Check for the missing Nomad events
- [ ] Handle lost, pending allocations
- [ ] Handle lost, running allocations and improve error detection.

**Comment by MrSerth** [comment]
[This page](https://developer.hashicorp.com/nomad/docs/commands/node/status#examples) lists the relevant options for the Desired Status and Client Status. It also shows, as you suggested, that there might be a client status`lost`, which we haven't seen in our logs. I also don't know why we don't see it, but I noticed that the `pending` status is only sent once the Nomad agent is available again (not when the connection is lost).

**Comment by mpass99** [comment]
> In a recent downtime of one Nomad Agent

In which? `Apr 17, 2023 8:56:49 AM UTC`

> Why do we not receive an Event with the ClientStatus lost and the DesiredStatus stop like usual?

I tested the scenario of an agent downtime on staging that was starting and running some allocations.
We can observe that for each starting and running allocations of that agent we receive a `lost` event: `Other Client Status` [POSEIDON-2M](https://codeocean.sentry.io/issues/4206026379/).

Also, we can confirm that `Started Runner is already in use` [POSEIDON-2G](https://codeocean.sentry.io/issues/4061207219/?referrer=github_integration) is thrown for every allocation of that agent that was running and used. This is caused by Nomad rescheduling lost allocations [[1]](https://discuss.hashicorp.com/t/understanding-job-restart-behaviour-on-lost-jobs/39353/2). This issue is discussed in #358.

But, the issue `Other Desired Status` [POSEIDON-2E](https://codeocean.sentry.io/issues/4052530553/?referrer=github_integration) is unclear. We receive it only twice for one specific allocation `68a7809d-95ae-05d4-1b5c-c3596a1156`. The Nomad events regarding this allocation are wild. This allocation was started on the agent that was going down. Then, we receive the `Other Client Status` for this allocation meaning that it is `lost`. Followed by an `Other Desired Status`-issue regarding this allocation from another Nomad agent. But also, we receive an event from the down agent that the `lost Tasks are running`. Other pending runners on that agent do not result in this issue.
I assume it might be a race condition / bug in Nomad. As this issue appears every couple of days, we might need to inspect this issue closer.

> - [ ] Handle lost, pending allocations

It feels like the context is too unclear for concrete measures. How should lost allocations be handled? On which Nomad event? The first or the third (in case of 3 Nomad restart attempts)? This behaviour should be discussed first in #358.
When this is decided, we might just cleanup our data of the lost allocation or additionally try to restart it, but from our current observations the **Open Question** is still not solved. In our staging environment we could just listen and handle the `lost` Nomad events and capture every stopped allocation. In the production environment we might not catch any stopped allocation as in the case of the 17th April downtime we did not receive any `ClientStatus: lost` event, but only `ClientStatus: pending` events. What they have in common is the `DesiredStatus: stop` and the `DesiredDescription: alloc is lost since its node is down`. This seems like the Nomad events are not reliable in terms of the `ClientStatus` (race condition) but in this case on the `DesiredDescription`/error.
This is in contrast with our current `ClientStatus`-focused architecture that might then be refactored to be focused on the `DesiredStatus`?! Or should we turn our back to the lower level `Allocation` events at all and only listen to the `Job` events?

**Comment by MrSerth** [comment]
During our discussion today, we decided the following:
- [ ] Retest the current behavior in production (to see whether a `ClientStatus: lost` or `ClientStatus: pending` event is received).
- [ ] Change Jobs to allow unlimited reschedules
- [ ] Add dedicated handling for `ClientStatus: lost`, so that these are not logged in Sentry as `Other Desired Status` [POSEIDON-2E](https://codeocean.sentry.io/issues/4052530553/?referrer=github_integration)

**Comment by mpass99** [comment]
> Retest the current behavior in production (to see whether a `ClientStatus: lost` or `ClientStatus: pending` event is received).

In our production test, Nomad behaved like in the staging environment. We received a `ClientStatus: lost` event for the running events. For two allocations, we received the `ClientStatus: pending` event with the description `alloc not needed due to job update`, but not event with `ClientStatus: lost`. This does not affect all `pending` allocations on that node. In this production test, the running allocations have been rescheduled, while the jobs for the two pending allocations have been removed.

Additionally, to these direct events, we receive `Allocation failure` (POSEIDON-13) and a mix of the errors `alloc is lost since its node is down`, `alloc not needed due to job update`, and `alloc is being migrated`.

> Add dedicated handling for `ClientStatus: lost`, so that these are not logged in Sentry as `Other Desired Status` [POSEIDON-2E](https://codeocean.sentry.io/issues/4052530553/?referrer=github_integration)

With #390 we filter and demote the specific error messages. But, which monitoring event remains to inform us if an agent is (permanently) down?

> Change Jobs to allow unlimited reschedules

With #390

**Comment by mpass99** [comment]
We experienced another production occurrence: `Jun 8, 10:14 PM`.
Node 2 (9:33 pm UTC) and 4 (10:14 pm) got unavailable. This was accompanied with many errors regarding #395. These errors are located at different times on the 8th and 9th.

**Comment by MrSerth** [comment]
For the time being, we consider this issue to be resolved. In the past months, we took multiple actions to improve the situation of lost and pending allocations and improved the Nomad event handling in Poseidon to have a better understanding of the current situation (and all available allocations). While we acknowledge that the situation might not be ideal yet, it is the best situation we could achieve with the available resources, considering this edge-case. If we learn more about further occurrences of cases we haven't handled yet, we might open a follow-up issue.
