### ISSUE TITLE
Unify terraform & Ansible commands

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#361]
- Do not use local variables when the result is only used once. Therefore, replace `icinga_security_groups` with `flatten`.
- Always pass security group object rather than a name. See outputs.tf for `http-s` module
- Update the usages of `ansible.builtin.file`
  - Remove the `recurse` option as it has (only) unwanted consequences for the file permissions
  - Omit the `mode` (file permissions) if it is equal to the default.
- Align empty line at the beginning of task yml files.

**Comment by MrSerth** [comment]
We completed the changes, so that this issue is done.
