### ISSUE TITLE
Nomad allocation exec does not respect PATH variable

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#366]
When executing a command in a Nomad allocation, changes to the PATH environment variable are not respected. This is not caused by Poseidon, I assume, but occurs independently.

<hr>

Consider the following Dockerfile:

```
FROM openhpi/docker_exec_phusion
ENV PATH $PATH:/workspace
```

Once a container with this Dockerfile has been built and started, connect through another shell and read the environment:

```
docker exec -it <id> env
```

While a native Docker exec works as expected (the PATH variable is adjusted), the same does not work for Nomad:

```
nomad alloc exec <id> env
```

**Comment by mpass99** [comment]
Hm, I cannot replicate the issue, for me the `PATH` variable is adjusted. also in Nomad
![See](https://user-images.githubusercontent.com/22845248/236705060-8f655c9c-628b-43ba-80a0-d4443323a236.png)

Is this issue affecting the Nomad agents?
Can you replicate the issue when using `docker exec -it <id> env` for the container/allocation started by Nomad or just when using the nomad cli?

**Comment by MrSerth** [comment]
Mh, you're right. I tested it once again today, and also wasn't able to reproduce it today. Even though I used some time (hours) to work around this issue, and reiterated on my image multiple times, it doesn't seem to be a general issue. Maybe I did something wrong, I cannot remember right now.

Let's close the issue for now and update it once it occurs another time.
