### ISSUE TITLE
Sentry Relay: Reboot might fail to start nginx

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#375]
We seem to have some race condition when starting nginx. We are explicitly binding on the external IPv6 address, which might fail if this address has not yet been assigned to the interface. In this case, we see the following logs:

```
May 13 17:27:46 sentry-relay-terraform systemd[1]: Starting nginx - high performance web server...
May 13 17:27:47 sentry-relay-terraform nginx[631]: nginx: [emerg] bind() to [2001:1438:4010:4700::5:e2]:80 failed (99: Cannot assign requested address)
May 13 17:27:47 sentry-relay-terraform systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
May 13 17:27:47 sentry-relay-terraform systemd[1]: nginx.service: Failed with result 'exit-code'.
May 13 17:27:47 sentry-relay-terraform systemd[1]: Failed to start nginx - high performance web server.
```

Following, the service is not retrying to start the instance. Manually restarting nginx worked, but until I did so, the whole nginx server was not available (and thus the relay).

**Comment by MrSerth** [comment]
I already started to look around how to resolve this issue. My quick search revealed two potential solutions:

- Adding an overwrite to the systemd config of nginx, making it dependent of the network being online. Potentially, the required change would be similar to the solution sketched in [this ticket](https://bugs.launchpad.net/bugs/1786974). 
- Allowing all applications, including nginx, to bind to a non-existing IP address, also known as non-local address. This would work as it would allow nginx to complete the boot process and hopefully just serve requests as soon as the address is available. Proceeding with this solution requires changing a kernel parameter, and is done separately for IPv4 and IPv6. If my search was correct, the setting can be changed [globally](https://serverfault.com/a/776009) or only [for a specific network interface](https://sysctl-explorer.net/net/ipv6/ip_nonlocal_bind/). 

I am undecided, but was slightly in favor of the second solution with a change to the kernel parameter (since it would allow nginx to start even when one interface is temporarily not available). While the man page for the respective entry warns about potential issues, it seems like it only affects an assumption developers could make: Namely, the availability of a given IP address on the host if binding this address is successful. nginx and other proxies are aware of this, so that they shouldn’t make any issues.

**Comment by mpass99** [comment]
Fixed by implementing an Ansible task that configures the second solution both for IPv4 and IPv6.
