### ISSUE TITLE
Sentry Relay: Events are missing

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#376]
Since I switched to the Sentry Relay, we miss many events. This can be easily observed when, for example, browsing performance views. While we should generally see a matching Ruby transactions for each JavaScript transaction, this is not the case.

However, in Puma's log (the CodeOcean web server), we see the following entries a lot:

```
E, [2023-05-13T19:00:06.025359 #3591] ERROR -- sentry: Transaction sending failed: the server responded with status 301
body: <html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.23.4</center>
</body>
</html>
```

and indeed, Nginx also shows this in the logs:

```
<IP>- - [13/May/2023:18:50:34 +0000] "POST /api/5667283/envelope/ HTTP/1.1" 301 169 "-" "sentry-ruby/5.9.0" "-"
```

I don't know what is happening, but it seems like nginx is accepting the request "on the wrong interface" or otherwise matching it up:

```
2023/05/13 18:45:23 [debug] 2721#2721: accept on 82.140.0.116:80, ready: 0
2023/05/13 18:45:23 [debug] 2721#2721: posix_memalign: 00005580EA3B0850:512 @16
2023/05/13 18:45:23 [debug] 2721#2721: *210 accept: 10.x.x.x:38730 fd:17
```

As a response, a redirect is returned:

```http
HTTP/1.1 301 Moved Permanently
Server: nginx/1.23.4
Date: Sat, 13 May 2023 18:45:23 GMT
Content-Type: text/html
Content-Length: 169
Connection: keep-alive
Location: http://srelay.codemoon.xopic.de/api/5667283/envelope/
```

I really don't know what is happening here, but we should fix it :). Probably, some nginx misconfiguration....

**Comment by MrSerth** [comment]
It seems like we have some issues with the DNS resolution.

curl shows:
```
curl -v sentry-relay-terraform.compute.internal
*   Trying 2001:1438:4010:4700::5:18:80...
* TCP_NODELAY set
* Connected to sentry-relay-terraform.compute.internal (2001:1438:4010:4700::5:18) port 80 (#0)
> GET / HTTP/1.1
> Host: sentry-relay-terraform.compute.internal
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.23.4
< Date: Sat, 13 May 2023 21:09:48 GMT
< Content-Type: text/html
< Content-Length: 169
< Connection: keep-alive
< Location: http://relay.codemoon.xopic.de/
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.23.4</center>
</body>
</html>
* Connection #0 to host sentry-relay-terraform.compute.internal left intact
```

Dig shows two different responses. One with the external addresses (from both environments!):
```
dig sentry-relay-terraform.compute.internal any

; <<>> DiG 9.16.1-Ubuntu <<>> sentry-relay-terraform.compute.internal any
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46212
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;sentry-relay-terraform.compute.internal. IN ANY

;; ANSWER SECTION:
sentry-relay-terraform.compute.internal. 0 IN A	82.140.0.116
sentry-relay-terraform.compute.internal. 0 IN A	82.140.0.107
sentry-relay-terraform.compute.internal. 0 IN AAAA 2001:1438:4010:4700::5:e2
sentry-relay-terraform.compute.internal. 0 IN AAAA 2001:1438:4010:4700::5:18

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sat May 13 21:17:00 UTC 2023
;; MSG SIZE  rcvd: 156
```

and one correct one with the internal address:
```
; <<>> DiG 9.16.1-Ubuntu <<>> sentry-relay-terraform.compute.internal any
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38543
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;sentry-relay-terraform.compute.internal. IN ANY

;; ANSWER SECTION:
sentry-relay-terraform.compute.internal. 0 IN A	10.x.x.x

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sat May 13 21:16:53 UTC 2023
;; MSG SIZE  rcvd: 84
```

These responses match my observation: First, I tried debugging the issue with Wireshark and listened on the specific internal interface (to reduce noise). However, during this capture, I did not find any HTTP 301 response. Obviously, my filter to the local network also removed the interesting part...

**Comment by MrSerth** [comment]
For now, I ~~fixed~~ prevented this issue by using the local IP address of the Sentry relay. This is working, but we should still investigate further (or reach out to our cloud colleagues).

**Comment by mpass99** [comment]
Thank you for identifying the issue and reducing it to a DNS problem already!

We may also reduce this issue to a local problem of resolving with the additional public interface. The issue appears only when resolving `sentry-relay-terraform.compute.internal` from the host itself, but is not limited to the sentry relay host. It also affects other hosts with multiple interfaces (`codemoon`).

> `;; SERVER: 127.0.0.53#53(127.0.0.53)`

For resolving this the local systemd-resolved DNS stub listener is requested. It is configured

```
resolvectl domain
Global:
Link 2 (ens3): compute.internal
Link 3 (ens4): compute.internal
Link 4 (docker0):
```

to use both interfaces for the `compute.internal` domain. In the debug logs (`systemd-resolved-230519.log`) you can see that the DNS server of both Links are requested for each dig request to the local resolver. The response that arrives first will be used as answer.

Unfortunately, all possible solutions to remove this search domain for the public interface found so far [[1]](https://unix.stackexchange.com/questions/606415/remove-a-dns-server-from-systemd-resolved) [[2]](https://askubuntu.com/questions/1068467/how-to-set-domain-search-on-ubuntu-18-04) have not been successful.

**Comment by MrSerth** [comment]
Thanks for digging into this. I reached out to our Cloud operator and asking for a hint. As a result, we found a mechanism to disregard the external DNS server and the search domain for the ens4 interface. The required changes are made in a pull request for our Ansible configuration.

**Comment by MrSerth** [comment]
Besides creating a suitable PR, I also reported the issue to our Cloud team (Reference: CL-732).

**Comment by MrSerth** [comment]
The corresponding Ansible PR has been merged and deployed. Additionally, I reverted the temporary change to use the IP address instead of the `compute.internal` hostname. Since this is everything we needed to resolve this issue (permanently), I am closing this issue. The Cloud ticket is unaffected by this closure, but we are no longer depending on the result of their investigation.
