### ISSUE TITLE
Sentry Relay: Session Replays are not stored

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#387]
When checking Sentry, I noticed that we are missing Session Replays since a while. Besides fixing some code-related issue with them, I tested that the relay is "not forwarding" these events correctly.

Here is a reproduction scenario:
1. Use Firefox
2. Visit `about:config`
3. Set `network.websocket.max-connections` to `0` (temporarily)
4. Now, head to any exercise on CodeOcean (`/implement` route)
5. Open your developer console, switch to "network" tab
6. Click on "Run" or "Score"
7. Check the messages sent to the sentry relay. You'll notice that a) an error, b) a transaction, and c) multiple replays should be sent. While the error and transaction appear on Sentry.io, the replay does not.

<img width="1840" alt="Bildschirmfoto 2023-06-02 um 22 33 41" src="https://github.com/openHPI/poseidon/assets/7300329/ba757017-6c17-4e46-9169-5c03588856c0">

**Comment by mpass99** [comment]
For the session replay requests the Sentry relay logs `DEBUG relay_server::utils::managed_envelope: dropped envelope: rate limited`. The rejection of the session replay requests is performed [here](https://github.com/getsentry/relay/blob/44f98d44cad29bd1676f1d91a13c97c88e8e235d/relay-server/src/actors/processor.rs#L2484-L2485) in the code of the Sentry Relay. Different from what one might expect, no rate limit got exceeded, but the Session Replay "Feature" is disabled by default. The feature can be enabled using the project configuration (see codeocean-terraform!126). This way the Sentry relay accepted the session replay envelope and logged "sending envelope to sentry endpoint".

By now, I was not able to identify the reason why our Sentry Dashboard still does not display the Session Replays :face_with_spiral_eyes:

**Comment by MrSerth** [comment]
Oh wow, this undocumented "feature" is really surprising.

> However, I see a huge potential for improving the documentation of the Sentry Relay!

I agree, I was also searching for something like this flag in the documentation before and couldn't find anything.

I just merged and deployed your changed configuration to our production environment. While I see the testing events from the staging environment already on Sentry, I would just suggest waiting another day to verify the issue with the production environment as well.

**Comment by MrSerth** [comment]
We finally receive replays again, so I consider this issue to be resolved.
