### ISSUE TITLE
Sentry Relay: Configure HTTP/3 with nginx

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#389]
According to [nginx quic demo](https://quic.nginx.org), the latest nginx version supports QUIC and HTTP/3. As we are already running the latest nginx mainline version, we can make use of it 😁.

Let's add HTTP/3 support for our nginx Ansible role.

**Comment by mpass99** [comment]
Thank you for bringing this up! I learned a lot about the new protocols :student: 
See `codeocean-terraform!128`

**Comment by MrSerth** [comment]
After resolving some issues with the unattended-upgrades (to get the latest version of nginx, that fixes an important bug related to the HTTP/3 TLS handshake), we have HTTP/3 working reliably 🥳.
