### ISSUE TITLE
Report Failed InfluxDB writing

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#395]
Report failed InfluxDB writing to Sentry by using the [`WriteFailedCallback`](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2/api#WriteFailedCallback).

**Comment by MrSerth** [comment]
Sounds good, thanks for checking. Do we need to add some dedicated (Sentry) error handling if the InfluxDB writing failed finally? To me, it sounds like do so already:

https://github.com/openHPI/poseidon/blob/9d13613f37be655d4593361a726f72ef7141f3c1/pkg/monitoring/influxdb2_middleware.go#L79-L83

This should also result in a Sentry error, right?

**Comment by mpass99** [comment]
Yes, the case of InfluxDB writing failing finally, should result in a Sentry error due to this condition. By now, we have not experienced this error.
