### ISSUE TITLE
Full resync with Nomad

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#399]
ToDo: Reevaluate necessity

<hr>

In the context of this issue a workaround for "too few idle runners" should be found and implemented. This workaround should create additional runners in cases in which we can be sure that we have too few (not just because one is currently starting).
Also, this workaround must actively report identified situations of too few runners.

**Comment by mpass99** [comment]
Such a workaround has been implemented with #486

**Comment by MrSerth** [comment]
The workaround implemented with #486 is working well. Hence, I would close this issue for now, since there is no immediate action to perform at this time.
