### ISSUE TITLE
Poseidon looses an environment after restart

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#408]
When unattended-upgrades restarts our systems (either Poseidon or the Nomad VMs; we don't know yet), all environments are temporarily lost. Only once a learner requests an execution, the respective environment is re-added dynamically (and then works as expected).

**Comment by mpass99** [comment]
In our (by now) one observed case, on the 17th July at 02:00:30 am UTC, Poseidon did not recover the execution environments. Instead, it threw the error: `Jul 17 02:00:30 msg="Error recovering the execution environments" error="couldn't load template jobs: couldn't load jobs: error listing Nomad jobs: Unexpected response code: 500 (No cluster leader)"`.

The reason for this is that we have configured our unattended-upgrades to restart our hosts at 2 am. Unlike with the download and the installation, we do not have a random delay for the reboot which leads to all hosts being rebooted at the same time.
In this case, the timing led to Poseidon fetching the execution environments when the Nomad server were in the election of their cluster leader. Therefore, the request failed.

I can thing of the following solutions:
1. Configure the unattended upgrades to keep `unattended_automatic_reboot` `true`, but drop `unattended_automatic_reboot_time`. Then, the host will reboot right after the upgrade (if required). When `unattended_apt_daily_upgrade_randomizeddelaysec` is high enough we can reduce the risk of startup race conditions.
2. Make the environment recovery mandatory for Poseidon. This way we would wait (and retry) for a successful recovery before continuing with the Poseidon startup. (A successful recovery can also create no environments, if non exist).

**Comment by mpass99** [comment]
> The recovery process would also be successful, when attempted from a clean Nomad environment, right? It's more about the successful connection to Nomad, not necessarily about receiving environment details? Do you see a simple mechanism to add such a retry mechanism (maybe reusing our existing approach for some retry tasks)?

Yes :+1:
