### ISSUE TITLE
Hide system environment variables / Add toggle

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#41]
With #27 and #39, we allowed access to (all) system environment variables with the intention to use those defined in the `Dockerfile`. Simultaneously, all other system variables are now accessible, especially those specific to our Nomad environment.

As outlined in [my comment](https://github.com/openHPI/poseidon/pull/39#issuecomment-971442550) I don't see an immediate call to action here but still room for improvement. Hence, we might investigate how to hide some system variables and could also think of allowing specific variables or introducing an HTTP query parameter such as `showSystemEnvironmentVariables` (see [proposal here](https://github.com/openHPI/poseidon/pull/39#issue-1055898994).

**Comment by mpass99** [comment]
Instead of using `env -` as before we could use `env -u ENV_VAR`. Another possibility could be Nomads [env.denylist](https://www.nomadproject.io/docs/configuration/client#env-denylist) or a configuration described in the [docs](https://www.nomadproject.io/docs/runtime/environment).
Also, we should consider what the use case and the priority of hiding the variables is.

**Comment by MrSerth** [comment]
Thanks, these are great additions. I would propose to have a quick oral chat about the use case and priority of the variables; maybe I miss something important here. Therefore, I think, that this issue is nothing that blocks us from going live with Poseidon for now 🙂.

**Comment by MrSerth** [comment]
As discussed, we consider this issue to have a low priority. When tackling it, we will first look into the env.denylist or close the issue otherwise.

**Comment by MrSerth** [comment]
We could use the `unset` approach we developed for AWS and invoke that command before switching the user.

**Comment by mpass99** [comment]
Is it still an acceptance criteria to have a HTTP query parameter to configure the behavior? I cannot imagine a use case to show the Nomad specific environment variables..

**Comment by MrSerth** [comment]
> Is it still an acceptance criteria to have a HTTP query parameter to configure the behavior? I cannot imagine a use case to show the Nomad specific environment variables..

No, probably not; I would leave that out for now and do not introduce a new parameter. Sure, having access to the variables might be nice for debug sessions, but I would just remove them through the API completely by now.
