### ISSUE TITLE
Out-Of-Memory on Poseidon VM

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#429]
Recently, I observed a variety of different errors with Poseidon, including [CODEOCEAN-T1](https://codeocean.sentry.io/issues/4421478383/), [CODEOCEAN-S9](https://codeocean.sentry.io/issues/4412338743/), [CODEOCEAN-S8](https://codeocean.sentry.io/issues/4412335958/), [CODEOCEAN-SR](https://codeocean.sentry.io/issues/4417388132/).

Those errors all appeared since Monday evening, where I performed a (manual) deployment of commit c0a3fb12c3d48ca2e3a8d59a5be1477b521a31e3 to our server. While first considering network issues, I now think we have a problem with our Poseidon VM (not necessarily with Poseidon, but I don't know yet). My first investigation showed: We have a memory issue!

Here is the overall system memory to that VM:

<img width="1706" alt="Bildschirmfoto 2023-08-26 um 16 41 20" src="https://github.com/openHPI/poseidon/assets/7300329/0e80a992-f155-4da8-889e-3b9a98416bb3">

Further, [the kernel log](https://github.com/openHPI/poseidon/files/12445596/oom.log) clearly shows that the OOM killer terminates Poseidon. We should investigate here immediately to restore regular operation.

**Comment by MrSerth** [comment]
Indeed, Poseidon seems to be responsible for the majority of memory:

<img width="1077" alt="Bildschirmfoto 2023-08-26 um 18 03 46" src="https://github.com/openHPI/poseidon/assets/7300329/aec331fc-2244-4005-baf0-55785a074520">

Shortly after, this already reads as

<img width="1077" alt="Bildschirmfoto 2023-08-26 um 18 21 51" src="https://github.com/openHPI/poseidon/assets/7300329/368247e3-3ae6-46e0-bc20-c2a3d3da75b1">

**Comment by mpass99** [comment]
With #430 we fix this specific issue.

Anyway, I think we should monitor goroutine leaks in general, i.e. by adding tests that count and compare the number of goroutines before and after. What do you think?

**Comment by MrSerth** [comment]
Thanks for fixing the issue (and deploying it already)!

Sure, if there is a method to check for leaked go routines, I'd go with that. Not sure how easy such a test is to achieve, but if you have an idea, I am very open to it. :+1:

**Comment by mpass99** [comment]
ToDo: Also check for shuffling the test order

**Comment by MrSerth** [comment]
> ToDo: Also check for shuffling the test order

We should potentially extract this into a dedicated issue, so that we can work on it in the future.

**Comment by mpass99** [comment]
Yes 👍 See #451
