### ISSUE TITLE
Nomad Event Stream failed when stopping Poseidon

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#432]
While investigating another issue, I noticed that Poseidon regularly faces an issue when being stopped. In my examples, I was starting Poseidon, kept it running for 10-15 seconds (with Nomad working as expected) and then stopped it again. In this scenario, I often (but not always) saw an error:

```
time="2023-08-28T22:40:40.827735Z" level=debug msg="Creating new runners" environment_id=10 package=environment runnersRequired=0
time="2023-08-28T22:40:40.828015Z" level=info msg="Starting server" address="127.0.0.1:7200" package=main
^C
time="2023-08-28T22:40:54.199813Z" level=info msg="Received SIGINT, shutting down ..." package=main
time="2023-08-28T22:40:54.199948Z" level=info msg="Server closed" error="http: Server closed" package=main
time="2023-08-28T22:40:54.200008Z" level=debug msg="Stopping CPU profiler" package=main
[Sentry] 2023/08/28 22:40:54 Event dropped due to noopTransport usage.
time="2023-08-28T22:40:54.200025Z" level=error msg="Nomad Event Stream failed! Retrying..." count=1 error="<nil>" package=runner
```

I am wondering about the last error "Nomad Event Stream failed!" What failed here (especially since the `error` is `nil`) and is this behavior expected?

**Comment by mpass99** [comment]
I was able to reproduce the behavior and am receiving the following logs on shutdown:
``` log
time="2023-11-17T15:08:40.930120Z" level=info msg="Received SIGINT, shutting down..." package=main
time="2023-11-17T15:08:40.930443Z" level=info msg="Server closed" error="http: Server closed" package=main
time="2023-11-17T15:08:40.930956Z" level=debug msg="Stopping CPU profiler" package=main
time="2023-11-17T15:08:40.931607Z" level=warning msg="Loading and synchronizing Runners failed! Retrying..." error="error receiving events: context canceled" package=environment
time="2023-11-17T15:08:40.935115Z" level=info msg="Stopped KeepEnvironmentsSynced" error="the retry context is done" package=environment
```
The changed log statement is likely caused by our recent refactoring in 6b69a2d73237867c1044796471e728da3182d1af. However, the main issue we should tackle in this issue remains: We receive the warning `Loading and synchronizing Runners failed!` even if it is normal behavior.

**Comment by MrSerth** [comment]
Indeed, the message changed with one of the refactorings. Nevertheless, you're on the right track.

As mentioned in the PR review for #498, I only was successful in reproducing the original issue with the CPU profiler being enabled (just to have that noted in this issue as well).
