### ISSUE TITLE
Sentry Missing WebSocket spans

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#438]
Related to #428 

Still, some WebSocket transactions are missing [[1]](https://codeocean.sentry.io/performance/codeocean:079384940a8f416a9a9b624c489e84bc/) [[2]](https://codeocean.sentry.io/performance/codeocean:faaa1fcf1bcb4e4c8cde3d6f6ec023d6) [[3]](https://codeocean.sentry.io/performance/codeocean:4a1568e7138647829c0858b1a05e8c63) [[4]](https://codeocean.sentry.io/performance/codeocean:2d638d310d0d488a8b7e4810f3d18b23) [[5]](https://codeocean.sentry.io/performance/codeocean:383be8f491d446fe858bc5793897dd9f) [[6]](https://codeocean.sentry.io/performance/codeocean:73dd123c4b4a4f0ab14c117522346f11) [[7]](https://codeocean.sentry.io/performance/codeocean:8ec71501d66740748520a27c8536ad33) [[8]](https://codeocean.sentry.io/performance/codeocean:7b55fb58e8804463ae614eb2f203ca56) [[10]](https://codeocean.sentry.io/performance/codeocean:4e009add137b440ab1b866d4a32b06d5)

Or even all transactions [[9]](https://codeocean.sentry.io/performance/codeocean:73a19816b8c742859266cf6c2362dac5)

In #428 we already found that the WebSocket transaction is the request with by far the biggest body size. This led to the Nginx body size limit being hit. Now, we cannot identify filtered requests in the Nginx log.

It seems like the WebSocket events are stored in Sentry [[11]](https://codeocean.sentry.io/performance/poseidon:a19d1cb80fb545208d8afabb6933b22a) but not linked in the `SubmissionsController#run` view [[12]](https://codeocean.sentry.io/performance/codeocean:26a0168ded8c46e79554d1d4dabecf42).

**Comment by mpass99** [comment]
Let's specify which transactions are missing.
- When browsing Performance > Poseidon > `GET /api/v1/runners/*/websocket` the spans within one transaction seem to be complete.
- When browsing Performance > CodeOcean > `SubmissionsController#run` the spans within one transaction seem to be complete but the span `websocket.client` should be expandable but (often) isn't.

For example: [Here](https://codeocean.sentry.io/performance/codeocean:b7c05fe641cb4d98bf251095a6002268/?limit=100&transaction=SubmissionsController%23run) we have a Poseidon transaction and via the trace navigator we can move to the `SubmissionsController#run`, but in [this view](https://codeocean.sentry.io/performance/codeocean:b7c05fe641cb4d98bf251095a6002268/) (only) the WebSocket span is not expandable.

I assume it's a Sentry issue (maybe caused by the high number of sub-spans 🤷 ) as the transaction is obviously reported to Sentry. @MrSerth What do you think?

**Comment by MrSerth** [comment]
Nice, thanks for that investigation! As usual, my response is two-folded:

1. Indeed, it appeared that only the linking of the WebSocket spans is missing in Sentry. When clicking around a little, I noticed something odd: The span entitled `view.process_action.action_controller` has two parts:
    1. The visible children, for example showing some database queries.
    2. A very hidden `+` sign next to the title. This `+` sign is clickable and shows the "missing" WebSocket span 🎉 

    Hence, the Sentry header added to the outgoing WebSocket request in CodeOcean is presumingly incorrect. Therefore, I debugged a little and created PR https://github.com/openHPI/codeocean/pull/2041 to fix that behaviour.
2. What about those cases where more than just the WebSocket trace was missing, for example [[9]](https://codeocean.sentry.io/performance/codeocean:73a19816b8c742859266cf6c2362dac5) (as noted in the original issue description)?
