### ISSUE TITLE
Send (OOM) kills to Sentry

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#452]
Currently, when Poseidon is killed, e.g., by the OOM killer, we do not get notified nor any Sentry event. Ideally, we would add some hook or other mechanism to get informed whenever Poseidon quits unexpectedly.

**Comment by MrSerth** [comment]
In order to address this issue, we want to tackle two different aspects:

- [ ] First, we want to add an `ExecStopPost`, checking the exit code of Poseidon and potentially creating a Sentry issue.
- [ ] Second, we want to formalize our memory monitoring introduced with #457, so that the threshold is customizable and can remain in the source code. This should allow enabling / disabling the monitoring at all. If a memory leak is detected, the information is written as an error to the log and sent to Sentry (if enabled).

**Comment by mpass99** [comment]
Should we also address setting up the systemd watchdog within this issue (or create a separate issue for it)?

**Comment by MrSerth** [comment]
Let's extract it to a dedicated issue, since it is not directly related to the OOM kills tracked in this one.
