### ISSUE TITLE
Another Out-Of-Memory Error on Poseidon

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#453]
We are experiencing another out-of-memory error on Poseidon, that should be investigated further.

I don't have many details to share, yet. The issues appeared first on Sunday, September 17th with release 39fc0f9. After rolling back to the previous commit 68cd8f43b451ac39ad55c272881f3db66f401156 (around 3:30pm CEST), the issue did not occur another time. This could point to one of the dependencies, but I am not sure about that either.

<img width="1713" alt="Bildschirmfoto 2023-09-17 um 15 40 43" src="https://github.com/openHPI/poseidon/assets/7300329/d092b790-63a9-4dd6-a90e-a86e27201add">

**Comment by MrSerth** [comment]
We have another occurrence of an OOM kill just from this morning (Sep 18 06:38:45). See more details with `cat /var/log/syslog | grep -A 50 -B 50 OOM`.

**Comment by mpass99** [comment]
Unfortunately, Poseidon's Log does not really help identify the memory leak. During the OOM kill, three actions were happening:
1. One running execution (next to 60338 others that day)
2. One runner stopped due to an inactivity timer (which happened also 5136 other times this day without problems)
3. One allocation event handling (23944 times that day)

Accordingly, I was also not able to reproduce the issue in the staging environment.
#457 might help identify the leak.

**Comment by MrSerth** [comment]
> Unfortunately, Poseidon's Log does not really help identify the memory leak. 

I feared that, but thanks for looking into it nevertheless. Besides the PR #457 you've just created, do we have a chance to analyze a core dump or (performance) profile? I am still hoping it would be possible to get a memory dump just before the memory is cleared, which might further assist us in debugging the cause.

**Comment by MrSerth** [comment]
Ah, thanks for investigating here! I just went ahead and disabled the profile sampling (by setting `profilessamplerate: 0.0`). With this, we should be able to confirm our assumption about the root cause. If this doesn't help, we could also consider downgrading the sentry dependency to limit the cause there.

**Comment by MrSerth** [comment]
It seems like the issue didn't occur another time, that's good! 🥳 

Nevertheless, I was further able to confirm that it is indeed a reproducible problem. Using CodeOcean and our Python 3.8 exercise (with `profilessamplerate: 1.0` in Poseidon), I was able to observe the issue locally. Running the attached [drawing.py](https://github.com/openHPI/poseidon/files/12677278/drawing.py.zip) multiple times caused the bug to appear. Still, not very easy to see, but something like 1 out of 10 (or 1 out of 7) caused the issue for me.

**Comment by mpass99** [comment]
You're right, thanks for drawing further attention to that. With the following configuration, I was able to reproduce the behavior (10/10):
- `profilessamplerate: 1.0`
1. Provide a runner `{"inactivityTimeout": 600,"executionEnvironmentId": 1}`
2. Create an execution with a time limit of 35s and let it exceed `{"command": "sleep 40","environment": {},"timeLimit": 35}`
3. Connect to the execution.

This creates the described memory leak in Sentry's `profiler.go`. Furthermore, this even easily allows to attach a debugger. As expected, neither break-condition is triggered and the loop runs endlessly.

**Comment by MrSerth** [comment]
Awesome, it's great to hear we have these simple reproduction steps, at least with Poseidon. Can we add a regression test for that, even when no DSN is set? This would at least allow us to identify the issue in the future.

And of course, we should probably now go one step further to avoid a memory leak even when the profiler is being used.

**Comment by MrSerth** [comment]
Today, we discussed this issue again. For now, we won't add a regression test, since this would mainly cover code originally written in the Sentry dependency. Nevertheless, we agreed to create a bug report (ideally with a minimal reproduction example independent of Poseidon) for the Sentry team to take a look at this issue.

**Comment by mpass99** [comment]
Submitted @ getsentry/sentry-go#724

**Comment by mpass99** [comment]
The published release `0.25.0` resolves this issue (tested with both the minimal example and [our Poseidon reproduction](https://github.com/openHPI/poseidon/issues/453#issuecomment-1732397940)). Therefore, we can think about updating this dependency and enabling the profile sampling again.

**Comment by mpass99** [comment]
Done with [3d87cfc](https://github.com/openHPI/poseidon/commit/3d87cfceeb858787d9bce5dce7a4b7b9c0fbc480) and `codeocean-terraform#8cbc9183`
