### ISSUE TITLE
Improve error handling for sending events to Influxdb 

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#479]
Recently, we lost some monitoring data (see #471 and #470) that were not sent to Influxdb. Besides improving the monitoring for system services (#471), we are also interested in understanding why we didn't see a Sentry event for Poseidon failing to send data to Influxdb.

Therefore, this ticket is about checking the Influxdb error handling in Poseidon.

**Comment by MrSerth** [comment]
[@mpass99 on October 6th 3:23 PM CEST](https://github.com/openHPI/poseidon/issues/471#issuecomment-1750676501):

> Just the logs contain `Oct  1 00:00:36 poseidon-terraform poseidon[34693]: 2023/10/01 00:00:36 influxdb2client E! Write proc: Retry buffer full, discarding oldest batch`

**Comment by mpass99** [comment]
> Interestingly, Poseidon also didn't report an error about failures of sending events to InfluxDB. This error is tracked in #479.

_Originally posted by @MrSerth in https://github.com/openHPI/poseidon/issues/471#issuecomment-1746350737_

That's because Poseidon reports this error just on `Trace`-level which is commonly not even stored in the log files.

https://github.com/openHPI/poseidon/blob/cb08787c7d20bbf6ffb710244a9da46b12dd5d91/pkg/monitoring/influxdb2_middleware.go#L77

If we would raise the log-level, we would have received the following output:
``` log
2023/11/23 14:03:07 influxdb2client E! Write error: Post "filtered": context deadline exceeded (Client.Timeout exceeded while awaiting headers), batch kept for retrying
time="2023-11-23T14:03:07.919428Z" level=warning msg="Retrying to write influx data..." error="filtered": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" package=monitoring retryAttempts=0
```

How should we improve this in the future? Should we (ab-)use Sentry for uptime monitoring? Should we somehow connect the InfluxDB unavailability to Poseidon's Health route? Or, should we rely on the recently introduced Icinga checks of the monitoring host itself?

**Comment by MrSerth** [comment]
I would actually differ between a retry and a permanent failure.

The code position and the exemplary log you provided are about a retry that is scheduled. I think, a Trace level is fine for this kind of message. However, my concern would be to get notified about a permanent failure, where no further retry is scheduled. In the original ticket text, I was referring to two occasions, where we actually lost data and you [confirmed](https://github.com/openHPI/poseidon/issues/479#issuecomment-1753028265) that data was actually discarded. Can we track _those_ occurrences better?

For the InfluxDB monitoring, I would probably rely more on the Icinga checks, but adding something to the health route is also a nice idea. Nevertheless, I think we should first nail down the actual issue before considering the different implementation strategies.

**Comment by mpass99** [comment]
> Can we track those occurrences better?

Unfortunately, I haven't found such a possibility. I've i.e. checked https://github.com/influxdata/influxdb-client-go/blob/master/internal/write/service.go. You can see there that the `errorCb` is the only callback for the influx client. It is only triggered when there is an (HTTP) error writing a batch. Independently, the client buffer for batches is handled.  
Let's consider an example: The client library handles one batch write after another. Suddenly, one batch write fails. In the `retryDelay` after the event, all batches are just stored in the buffer and not even tried to be written. Whenever the buffer is full, the oldest batch is discarded - without a callback, just with a log statement.  
The only option I see is to intercept and parse our own stderr stream, and this doesn't sound like a clean solution.  
Besides this, we can influence the process by decreasing the `retryDelay`, increasing the `retryBufferLimit`, or handling the `WriteFailedCallback` as more severe (as every dropped batch is preceded by at least one callback call).

**Comment by MrSerth** [comment]
>> Can we track those occurrences better?
>
> Unfortunately, I haven't found such a possibility.

That's sad, of course, but okay.

> Independently, the client buffer for batches is handled.

Yes, I see that. It doesn't feel very smart, but alright -- nothing we can change.

> The only option I see is to intercept and parse our own stderr stream, and this doesn't sound like a clean solution.

No, that doesn't sound clean at all. Then, we'd rather need to accept some unreliability here.

> Besides this, we can influence the process by decreasing the `retryDelay`, increasing the `retryBufferLimit`, or handling the `WriteFailedCallback` as more severe (as every dropped batch is preceded by at least one callback call).

Influencing sounds good. I get the increase of the `retryBufferLimit` (we'll just store more events before discarding, similar to our Sentry relay), and the severity of the `WriteFailedCallback` (i.e., in Sentry logging or so), since this would provide some better feeling for the occurrence. However, I am not sure about decreasing the `retryDelay`: The idea would be that a shorter delay increases the possibility to deliver an event successfully (since a retry would be closer to the "recovery" of the service, so that less events queue up)? Mh, yes, could be. 

Probably, I would proceed with a combination, maybe except the severity of the `WriteFailedCallback`. The other two sound valid and like a good idea. For the severity of the `WriteFailedCallback`, I am fearing to generate too much "noise" in the logs that we won't action. Another idea: Can we add a monitoring, similar to the RAM usage, that is observing the InfluxDB queue size? Either, by measuring it directly (ideally) or indirectly through RAM usage / ...?

**Comment by mpass99** [comment]
See #510 for the adjusted `retryBufferLimit` and `retryDelay`.

> Can we add a monitoring, similar to the RAM usage, that is observing the InfluxDB queue size?

> by measuring it directly

No, as Golang keeps the modularity quite well, and therefore influxdb's internal queue is not accessible from outside the package.

> indirectly through RAM usage

I would argue, it's too imprecise (and therefore generating noise we won't address). Higher memory usage can indicate a higher usage of Poseidon as much as network issues leading to full Sentry or Influx buffers.

**Comment by MrSerth** [comment]
Okay, I see. That's plausible; let's observe the changes and hope we don't have many further network issues that could cause such errors. Hence, I am fine closing this issue with #510.
