### ISSUE TITLE
Updating the environment leads to too many runners

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#48]
Updating an execution environment consists of three steps.
Register the environment at Nomad, update the existing runners and scale the number of runners if required.

https://github.com/openHPI/poseidon/blob/705d35802707c777e27b324501fe4731416d2937/internal/environment/manager.go#L130-L141

In some cases the runners (/Allocations) need to be restarted in step two. But (even if our request to Nomad is synchronous) the allocations are restarted asynchronously. Poseidon is informed about the shutdown and the restart of the allocations. This time span can also be longer for example when a new docker image needs to be pulled.

But since the requests are finished early we finish step two before all runners are restarted. Then in step three Poseidon thinks it needs more runners and request new ones. This may lead to the pool size being doubled when an environment is updated, even though this was not requested.

**Comment by MrSerth** [comment]
Nice edge case you discovered here. I was ideating a few minutes on possible solutions but didn't come up with a great solution. Probably we need to handle updates to the size specifically and only scale by the relative change...

**Comment by mpass99** [comment]
Yes, these are two good solutions.
- A separate route for scaling would reduce complexity, which is nice at this point. 
- Scaling with a relative change would also work. My only concern is that the pool size would become smaller without us noticing. If Nomad stops a job now and then (perhaps not realistic), then over time the CodeOcean configuration of the pool size would deviate from the actual pool size in Poseidon without us being able to change anything. (This is what we would have to keep in mind with this solution.)

To make the triple complete, here is another but not so great proposal.
- When registering a job we state `It registers the job and waits until the registration completes`. So I assume that when the function finished the Job is created and I get the error if there is one. That's not true. The Job is just registered and not created. So for example if the docker image cannot be pulled we don't receive this error here.
With a bit more implementation work we can adjust the register function to wait even for the allocation to be created (as we already receive this information via the event stream).

Maybe I would go with the first solution :man_shrugging: What do you think?

**Comment by MrSerth** [comment]
I also thought of using the event stream, making some requests slower and blocking by waiting for the final result. For updating allocations, this is totally acceptable IMHO.

 > - Scaling with a relative change would also work. [...]

You came up with another idea I didn't had. You're talking about using relative numbers in the request from CodeOcean to Poseidon, right? This might, indeed, sum up errors over time. My idea was a little different: I thought of first getting the allocation count for the execution environment (as already done in the first line of `UpdateRunnerSpecs`) and use this as a base (say `n`).

- If we want to decrease runners, we could first remove the number of unwanted allocations (`n - desired`) and then update the remaining allocations.
- If we want to increase runners, we first update all existing runners and then only create as much runners as not already present (`desired - n`).

This would delegate the (re)creation of runners to Nomad and (probably?) get the right amount of allocations if everything worked well. In case of errors, this is not a perfect solution as we still don't consume the event stream. If we want to make it reliable, we probably need to process the event stream...

**Comment by MrSerth** [comment]
As expected (and intended), with #33 all runners get recreated with their latest execution environment when synchronizing an environment. However, as a consequence, each synchronization will create too many runners (as described in this issue). Not a big deal, but an interesting observation.

**Comment by mpass99** [comment]
With issue #69 and the solution we thought of (remove all runners and recreate them) this should be solved either.
