### ISSUE TITLE
Improve reliability of test pipeline

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#52]
We should improve our CI to reduce the number of false-positive failures. Mostly, the e2e tests are flaky and fail randomly, but sometimes the (unit) tests are also failing. See [previous attempts of this test run](https://github.com/openHPI/poseidon/actions/runs/1508904639) for more details

**Comment by mpass99** [comment]
- 2 failures are due to the flaky test TestExecuteInteractivelyTestSuite/TestSendsSignalAfterTimeout
- 6 failures are due to the e2e tests - but not due to flaky test cases but due to a "socket hang up" error
