### ISSUE TITLE
Extend statistics

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#67]
https://github.com/openHPI/poseidon/pull/65

> > I assume that we won't send anything to Sentry in this case, right?
> 
> Yes, based on a normal termination, I would not have sent anything to Sentry; although it would be exciting to see how often this occurs. Should we rather log it at "warning" level?

> I see the interest but would rather not do it (at least not via Sentry). For one, Sentry is more dedicated to error tracing, and (therefore) the pricing model is based on each event. As a consequence, "counting" via Sentry might get expensive and as a project, we have an overall error limit per month (for all projects). Do you have another idea to log / count?

> We already have a "statistics" route. We could create a statistics controller and count things like "How often is which route requested" or "How often is the error code missing". With such a controller we could also provide an prometheus endpoint.
However, as this is a bit of work for currently not that much added value, I would assign it a low priority.

> I agree. Let's move this discussion into a dedicated issue and add it with a low priority. For these, we might also need to check for persistence/server restarts (depending on the concrete implementation).

**Comment by mpass99** [comment]
What is the scope of this issue? Please check what you think :)
- [ ] We use the [influxdb go client](https://github.com/influxdata/influxdb-client-go) to send events
- [ ] to the enpoint that is defined by two `statistics` config entries (url, token).
- We send events for
    - [ ] usage of the health route
    - [ ] usage of the version route
    - [ ] usage of the statistics route
    - execution environment
        - [ ] usage of the execution environment routes
        - [ ] Current environment count (Event on change)
        - [ ] creation of an environment
        - [ ] update of an environment
        - [ ] deletion of an environment
    - runner
        - [ ] Provide a runner event
        - [ ] Destroy runner event
        - [ ] Update files
        - [ ] Execute
        - [ ] WS connect
- Which information do the events contain?
    - [ ] Environment type (Nomad, AWS)?
    - [ ] Environment id
    - [ ] Environment data (image, PoolSize, CPULimit, MemoryLimit, NetworkAccess, ExposedPorts)
    - [ ] Runner id
    - [ ] Successful vs failing
    - [ ] Request (/WS connection) duration
        - [ ] Separate middleware event or in total only one event per request
    - [ ] Request size (fs update)
    - [ ] Response size
- [ ] We create useful Grafana dashboards

**Comment by MrSerth** [comment]
I like these, thanks for proposing such a detailed list! Let's start with the first implementation of the runner statistics and move the Grafana dashboard to a new ticket (so that both are independent of each other).
