### ISSUE TITLE
Enabled Network fails silently

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#78]
Currently no execution environments with the options `"networkAccess": true,
    "exposedPorts": [42, 1337]` can be created.
This reveals two errors: The fact that this is not possible (1) and the fact that this happens unnoticed (2).

1. When requesting such an execution environment we can see the failing jobs in the Nomad UI. We can see the error message: `failed to setup alloc: pre-run hook "network" failed: failed to configure networking for alloc: failed to configure network: failed to find plugin "bridge" in path [/opt/cni/bin]`
2. When requesting such an execution environment we get a normal `201 Created` response. When we take a look at [the server log](https://github.com/openHPI/poseidon/files/7739160/cannotCreateExecutionEnvironmentWithEnabledNetwork.txt) we notice that we first receive a `job-register complete` evaluation for the template job and the one requested runner. Then the response to us is written. Only 6s afterwards Poseidon is notified that the allocations actually failed.
Users of Poseidon have no chance to find out about it. Also in the list of Execution Environments, the environment just created is displayed normally. At the most, the Statistic Route could give a hint that the idle runners remain at 0. This way also one e2e test is fooled.

**Comment by MrSerth** [comment]
I added some documentation with #79 and performed these steps on all systems (staging and production). That resolved the immediate issue for now.
