### ISSUE TITLE
AWS refactoring towards interactive input and timeout

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#98]
At this point we can just start an AWS function that streams it output to us.
By switching from these static requests to a kind of reverse communication, e.g. by the AWS function establishing a WS Connection to Poseidon. Interactive elements such as inputs and timeouts can be implemented.

It would also make #97 easier, as we would then not need a WebSocket API, but only an HTTP API that supports mTLS.

**Comment by MrSerth** [comment]
Based on our findings in #218, this issue became obsolete and won't be tackled (in the current form). Therefore, I am closing it for now.
