### ISSUE TITLE
AWS: Dynamically create Execution environments

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#99]
At this point, AWS environments are created statically in the AWS SAM template

https://github.com/openHPI/poseidon/blob/683b4681b86c0212239328d5d79c9157b70412d8/deploy/aws/template.yaml#L58

However, it would also be conceivable in the future that - in addition to [the optimised Lambda runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) - any Docker containers would also run in AWS.

**Comment by MrSerth** [comment]
Based on our findings in #218, this issue became obsolete and won't be tackled (in the current form). Therefore, I am closing it for now.
